name: eypop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages..
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.7+47

environment:
  sdk: ">=2.16.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter

   # B4A SDK
  parse_server_sdk_flutter: ^9.0.0

  # Agora Calling / Permission / Ringtone
  permission_handler: ^11.3.1
#  agora_rtc_engine: ^6.3.1
  agora_rtc_engine:
    git:
      url: https://github.com/costaaaaaa/Agora-Flutter-SDK.git
      ref: fix_foreground_media_service

  flutter_local_notifications: ^17.2.3
  audioplayers: ^6.0.0
  flutter_callkit_incoming: ^2.5.0

  # Image
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  flutter_svg: ^2.0.10+1
  image_picker:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/image_picker/image_picker
  image_crop:
    git:
      url: https://github.com/VocsyJay/image_crop.git
  # File
  file_picker: ^8.0.3
  syncfusion_flutter_pdfviewer: ^25.2.4

  # Video
  video_thumbnail: ^0.5.3
  flick_video_player: ^0.8.0

  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  firebase_messaging: ^14.9.2

  # UI
  flutter_slidable: ^3.1.0
  flutter_screenutil: ^5.9.1
  flutter_holo_date_picker: ^1.1.3
  modal_progress_hud_nsn: ^0.5.1
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.4
  get_storage: ^2.1.1
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.2
  pin_code_fields: ^8.0.1
  flutter_native_splash: ^2.4.1

  # VIDEO CALL
  wakelock_plus: ^1.2.5
  screen_protector: ^1.4.2

#  sms_autofill: ^2.2.0
#  alt_sms_autofill: ^1.0.0
#    git:
#      url: https://github.com/VocsyJay/sms_autofill.git
#      ref: jay
#      Commit: e7b94a7bc9e4e060b9e16b8d653f7b9cece30952

  card_swiper: ^3.0.1
  blurrycontainer: ^2.1.0
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  vocsy_esys_flutter_share: ^1.0.2
  shimmer: ^3.0.0
  csv: ^6.0.0
  archive: ^3.6.1

#  local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #STATE_MANEGEMENT
  get: ^4.6.6
  provider: ^6.1.2
  visibility_detector: ^0.4.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  change_app_package_name: ^1.1.0
  intl: ^0.20.2

  #FIREBASE
  flutter_facebook_auth: ^6.2.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  firebase_analytics: ^10.10.5
  #payment
  in_app_purchase:  ^3.2.0
#    git:
#      url: https://github.com/flutter/plugins.git
#      path: packages/in_app_purchase/in_app_purchase
#      ref: main


  html: ^0.15.4
  #Notification
  streams_channel3: ^1.0.1
  in_app_notification: ^1.1.2
  firebase_crashlytics: ^3.5.5
  firebase_dynamic_links: ^5.5.5
  googleapis_auth: ^1.6.0

  # INFO
  flutter_device_id: ^1.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/eypopNewIcon.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  dependency_validator: ^4.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0


dependency_overrides:
  js: ^0.7.1
  uuid: ^4.4.0
  http: ^1.2.1
  meta: ^1.16.0
  package_info_plus: ^8.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/Icons/
    - assets/Logos/
    - assets/fonts/
    - assets/flags/
    - assets/jsons/
    - assets/
    - assets/videos/
    - assets/audio/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RB
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RR
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RM
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: HL
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.ttf
    - family: HR
      fonts:
        - asset: assets/fonts/HelveticaNeueRegular.ttf
    - family: HB
      fonts:
        - asset: assets/fonts/HelveticaNeueBold.ttf
    - family: HM
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

